in2code-de/femanager

Resources/Public/JavaScripts/Femanager.js, Resources/Public/JavaScripts/Validation.js
Pass $ as parameter to prevent error message "$ is not a function" when jQuery.noConflict() is used
=> [BUGFIX] Fix for jQuery.noConflict()

Classes/Domain/Validator/AbstractValidator.php, Classes/Domain/Validator/PasswordValidator.php, Classes/ViewHelpers/Validation/IsRequiredFieldViewHelper.php
=> [TASK] Get CONFIGURATION_TYPE_SETTINGS from ConfigurationManager

Classes/ViewHelpers/Form/TextfieldViewHelper.php
=> [BUGFIX] Do not override removed method in TextfieldViewHelper

Configuration/TCA/Overrides/fe_users.php
=> [BUGFIX] date_of_birth requires default value

Configuration/TypoScript/Main/setup.txt
=> Add a note for login problems in typoscript

Classes/Domain/Service/SendMailService.php
Would be nice if you could add these signal to the SendMailService so that it's possible to change different values of a mail right before sending and invoke something right after sending.
=> Add signal beforeSend + afterSend

Classes/ViewHelpers/Misc/GetFirstViewHelper.php
fix typo in arguemnt registration
=> [BUGFIX] Update GetFirstViewHelper.php

Resources/Private/Partials/Misc/FormErrors.html
=> [BUGFIX] Fix translation of field names in form errors

Classes/Controller/InvitationController.php
missing action before category
=> [BUGFIX] redirectStep1

Classes/Controller/NewController.php
=> BUGFIX: Allow to configure redirect for admin confirmation request

Classes/Controller/UserBackendController.php, Classes/Utility/BackendUserUtility.php, Resources/Private/Templates/UserBackend/List.html
UserTS:
tx_femanager.UserBackend.enableLoginAs = 1
Additionally it shows the "login as" icon only if it's usable for this user.
Closes: #134
=> Add possibility to use loginAs as editor with UserTS

Classes/Controller/AbstractController.php, Classes/Controller/EditController.php, Classes/Controller/InvitationController.php, Classes/Controller/NewController.php, Classes/Domain/Repository/PluginRepository.php, Classes/Domain/Service/FinisherService.php, Classes/Domain/Service/SendMailService.php, Classes/Domain/Service/SendParametersService.php, Classes/Domain/Validator/AbstractValidator.php, Classes/Domain/Validator/PasswordValidator.php, Classes/Finisher/FinisherRunner.php, Classes/Finisher/SaveToAnyTableFinisher.php, Classes/Finisher/SendParametersFinisher.php, Classes/Utility/BackendUtility.php, Classes/ViewHelpers/Be/GetClassNameOnActionViewHelper.php, Classes/ViewHelpers/Be/IsConfirmationModuleActivatedViewHelper.php, Classes/ViewHelpers/Be/IsResendUserConfirmationRequestActivatedViewHelper.php, Classes/ViewHelpers/Condition/IsBackendAdministratorAuthenticationViewHelper.php, Classes/ViewHelpers/Form/GetCountriesFromStaticInfoTablesViewHelper.php, Classes/ViewHelpers/Form/GetCountriesViewHelper.php, Classes/ViewHelpers/Misc/CaptchaEnabledViewHelper.php, Classes/ViewHelpers/Misc/ExplodeViewHelper.php, Classes/ViewHelpers/Misc/JsonEncodeViewHelper.php, Classes/ViewHelpers/Misc/RequestViewHelper.php, Classes/ViewHelpers/Misc/UpperViewHelper.php, Classes/ViewHelpers/Repository/GetFirstViewHelper.php, Classes/ViewHelpers/Validation/IsRequiredFieldViewHelper.php, Configuration/TypoScript/Main/setup.txt, composer.json
This pull request updates composer.json, and updates annotations, typoscript and mail sending to be compatible with TYPO3 v10.
=> Fix some v10 incompatibilities 

composer.json, ext_emconf.php
* Move package in composer.json from require-dev to require
* Move extension key in ext_emconf.php from suggests to depends
Fixes: #281
=> Add dependency of "static_info_tables"

Classes/Domain/Validator/ServersideValidator.php
=> [BUGFIX] return true for FileReferences

.ddev/commands/host/initialize, .ddev/commands/web/typo3, .ddev/commands/web/typo3cms, .ddev/config.yaml, .ddev/docker-compose.typo3.yaml, .ddev/typo3/AdditionalConfiguration.php, .ddev/typo3/config.yaml, config/sites/main/config.yaml, readme.md
Add ddev setup and configuration for local development
=> [TASK] Add ddev setup for local development

Documentation/Features/NewFields/Index.rst
* Include model and override default controller with TYPO3 10.4.x
* Own Controller Files with PHP 7.4 / TYPO3 10.4.x
=> [TASK] Add examples for extending femanager with TYPO3 10.4

Classes/Controller/AbstractController.php, Classes/Controller/AbstractFrontendController.php, Classes/Controller/EditController.php, Classes/Controller/InvitationController.php, Classes/Controller/NewController.php, Classes/Controller/UserController.php
=> [BUGFIX] Use ratelimiter service only in FE context

Configuration/FlexForms/FlexFormPi1.xml, Resources/Private/Language/locallang_db.xlf
=> [TASK] Add username to sort user list

Classes/Controller/AbstractController.php
=> [BUGFIX] Use array_merge to keep array structure

Classes/Domain/Model/User.php
Signed-off-by: Thomas Löffler <loeffler@spooner-web.de>
=> Set DateTime to Jan 1st 1970 if crdate is null

Classes/Controller/AbstractController.php
Added the possibility to translate the subject of the confirmation mail to the user
=> subject translation for createUserConfirmationMail

Classes/Controller/AbstractController.php
fix issue:
Redirect after user-confirmation-mail don't work #252
=> Fix link generation in general redirect method

Configuration/TCA/Overrides/fe_users.php, Resources/Private/Language/locallang.xlf, Resources/Private/Language/locallang_db.xlf, Resources/Private/Partials/Fields/Gender.html, Resources/Private/Partials/Mail/UserProperties.html, Resources/Private/Templates/Email/UpdateNotify.html, Resources/Private/Templates/Email/UpdateRequest.html, Resources/Private/Templates/User/List.html, Resources/Private/Templates/User/Show.html
=> [FEATURE] Add divers as gender

Classes/ViewHelpers/Form/GetCountriesFromStaticInfoTablesViewHelper.php, Resources/Private/Partials/Fields/Country.html
=> [FEATURE] Add possibility to set preferred or limited countries to selector

Classes/Controller/NewController.php
=> [BUGFIX] If user confirmation sent, do not send admin confirmation

Classes/Domain/Repository/UserRepository.php
=> [BUGFIX] Use exact email to check for resending confirmation mail

Classes/Event/BeforeMailSendEvent.php
To enable a "clean" solution for e.g. #384
=> Add setter to allow modification of email object inside event listeners

Documentation/Features/NewFields/Index.rst
I am sorry, my last PR was totally wrong!
After I just solved that during a v10 upgrade, I wanted to provide it to the docs but I was too tired obviously.
=> [BUGFIX] correct v10 Extbase persistence config

Classes/Utility/FrontendUtility.php, Classes/Utility/UserUtility.php, Tests/Unit/Utility/FrontendUtilityTest.php
Resolves  #385
Thx to https://github.com/ute-arbeit
=> [BUGFIX ]Make forceValues work for field names with underscores

Classes/Domain/Repository/PluginRepository.php, Classes/Exception/NotPaginatableException.php, Classes/ViewHelpers/Be/GetClassNameOnActionViewHelper.php, Classes/ViewHelpers/Form/SelectViewHelper.php, Classes/ViewHelpers/Form/TextfieldViewHelper.php, Classes/ViewHelpers/Misc/CaptchaEnabledViewHelper.php, Classes/ViewHelpers/Pagination/PaginateViewHelper.php, Classes/ViewHelpers/Pagination/UriViewHelper.php, Classes/ViewHelpers/Validation/AbstractValidationViewHelper.php, Configuration/FlexForms/FlexFormPi1.xml, Resources/Private/Partials/Misc/Pagination.html, Resources/Private/Templates/UserBackend/Confirmation.html, Resources/Private/Templates/UserBackend/List.html, Resources/Private/Templates/UserBackend/ListOpenUserConfirmations.html, composer.json
some more steps to improve TYPO3 v11 compatibility
inspired by EXT:lux migration
=> migrate PaginateViewhelper / ControllerContext / ObjectManager-get

Classes/Domain/Repository/UserRepository.php
=> [BUGFIX] Remove "endtime" for check of unique in db

Documentation/Features/NewFields/Index.rst, Documentation/Features/NewValidators/Index.rst
Update to use in TYPO3 v10
* Update section for extending femanager with own fields
* Update section for extending femanager with custom validation
=> [TASK] Update docs section for extending femanager

Classes/ViewHelpers/Be/GetClassNameOnActionViewHelper.php
Fixes a typo that prevents the BE module to load...
=> Fixes an annoying typo that break the BE module to load!

Classes/Controller/UserBackendController.php, Classes/Utility/BackendUserUtility.php
=> [BUGFIX] Prevent undefined array key "enableLoginAs"

Classes/Domain/Repository/UserRepository.php
Check user in order to prevent method_exists call on null
=> Check $user before calling method_exists

readme.md
I removed the last two images as those were not available anymore.
=> [BUGFIX] Fix image URLs in README.md

Classes/Domain/Model/User.php, Resources/Private/Language/locallang.xlf, Resources/Private/Templates/UserBackend/List.html
=> [FEATURE] Add column "inactive since" to backend list

.github/workflows/testing.yaml, Classes/Utility/UserUtility.php, composer.json
Fixes the Object Supper, two use statements were missing
=> [BUGFIX] Fixed Object Support for getDirtyPropertiesFromUser()

Classes/Controller/AbstractController.php, Classes/Domain/Service/SendMailService.php, Classes/Domain/Service/SendParametersService.php, Classes/Finisher/SaveToAnyTableFinisher.php, Classes/Finisher/SendParametersFinisher.php
=> [FIX] Fixes reaction when no typoscript configuration is set for redirect

Resources/Private/Templates/UserBackend/List.html
=> [BUGFIX] use proper colspan in user backend list table header

Classes/Domain/Validator/ServersideValidator.php
=> [BUGFIX] errorClass attribute not working

Classes/Domain/Service/SendMailService.php, Classes/Event/BeforeMailBodyRenderEvent.php
To be able to modify e.g. the standalone-view of an email before the body is rendered, it would be nice if you could add the event I've created.
=> Please add BeforeMailBodyRenderEvent

Resources/Private/Partials/Mail/UserProperties.html, Resources/Private/Templates/Email/UpdateNotify.html, Resources/Private/Templates/Email/UpdateRequest.html
=> [TASK] Use semantic HTML for tables in the emails

Resources/Private/Partials/Fields/Address.html, Resources/Private/Partials/Fields/CaptchaField.html, Resources/Private/Partials/Fields/City.html, Resources/Private/Partials/Fields/Company.html, Resources/Private/Partials/Fields/Country.html, Resources/Private/Partials/Fields/DateOfBirth.html, Resources/Private/Partials/Fields/Email.html, Resources/Private/Partials/Fields/Fax.html, Resources/Private/Partials/Fields/FirstName.html, Resources/Private/Partials/Fields/Gender.html, Resources/Private/Partials/Fields/LastName.html, Resources/Private/Partials/Fields/MiddleName.html, Resources/Private/Partials/Fields/Name.html, Resources/Private/Partials/Fields/Password.html, Resources/Private/Partials/Fields/State.html, Resources/Private/Partials/Fields/Telephone.html, Resources/Private/Partials/Fields/Terms.html, Resources/Private/Partials/Fields/Title.html, Resources/Private/Partials/Fields/Usergroup.html, Resources/Private/Partials/Fields/Username.html, Resources/Private/Partials/Fields/Www.html, Resources/Private/Partials/Fields/Zip.html
This is a pre-patch to adding more specific input types and autocomplete attributes to improve mobile usage, accessibility and autocomplete behavior.
=> [TASK] Improve the code formatting of additional input attributes

Classes/Controller/AbstractController.php, Classes/Controller/EditController.php
This should get the Rector CI job green again.
=> [TASK] Apply the latest Rector fixes for TYPO3 11LTS

Resources/Private/Templates/Edit/Edit.html, Resources/Private/Templates/Invitation/Edit.html, Resources/Private/Templates/Invitation/New.html, Resources/Private/Templates/New/ConfirmCreateRequest.html, Resources/Private/Templates/New/New.html, Resources/Private/Templates/New/ResendConfirmationDialogue.html
=> [TASK] Mitigate browser "spell jacking" in form elements

Resources/Private/Partials/Fields/Password.html
=> [TASK] Add autocomplete attribute to password fields

Resources/Private/Partials/Fields/Address.html, Resources/Private/Partials/Fields/City.html, Resources/Private/Partials/Fields/Company.html, Resources/Private/Partials/Fields/DateOfBirth.html, Resources/Private/Partials/Fields/Email.html, Resources/Private/Partials/Fields/Fax.html, Resources/Private/Partials/Fields/FirstName.html, Resources/Private/Partials/Fields/LastName.html, Resources/Private/Partials/Fields/MiddleName.html, Resources/Private/Partials/Fields/Name.html, Resources/Private/Partials/Fields/Telephone.html, Resources/Private/Partials/Fields/Title.html, Resources/Private/Partials/Fields/Username.html, Resources/Private/Partials/Fields/Www.html, Resources/Private/Partials/Fields/Zip.html
This helps accessibility, autocompletion, and usage on mobile devices.
Also fix an incorrect type.
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
Releases: v7, main
=> [FEATURE] Add type and autocomplete information to input fields

Resources/Private/Partials/Mail/UserProperties.html
In Partial UserProperties.html was a missing  wrap `<f:if>...</f:if>` around the `user.gender` property. I added it.
=> Add missing if clause in UserProperties.html

Classes/Controller/NewController.php
=> [BUGFIX] fix response object usage

Classes/Controller/UserBackendController.php, Documentation/Features/ResendUserConfirmationRequest/Index.rst, Documentation/Installation/Index.rst
Access check for backend operations are now unified and support rekursive lsting of frontend users
branch: 67114 confirmation tab
=> [REFACTOR] unify checkPageAndUserAccess

Classes/Controller/AbstractController.php, Classes/Controller/UserBackendController.php, Classes/Controller/UserController.php, Classes/Domain/Model/User.php, Classes/Event/ImpersonateEvent.php, Classes/Utility/UserUtility.php, Resources/Private/Templates/UserBackend/List.html, ext_localconf.php, ext_typoscript_setup.typoscript
Resolves #592, Resolves #454
Related: https://projekte.in2code.de/issues/57124
=> [BUGFIX] Restore function to impersonate frontend user (loginAs)

Classes/Controller/AbstractController.php, Classes/Domain/Validator/AbstractValidator.php, Classes/Domain/Validator/ServersideValidator.php, Resources/Private/Partials/Fields/Image.html
=> [BUGFIX] Make upload work again

Resources/Private/Templates/Email/CreateUserConfirmation.html
=> [BUGFiX]  CreateUserConfirmation.html refers to non-existing label 

Classes/Controller/AbstractController.php
=> [BUGFIX] TypoScript setting removeFromUserGroupSelection

Classes/Utility/UserUtility.php
thx to lochmueller
resolves #478
=> [BUGFIX]  Exception by selecting wrong hashing integration

Classes/Controller/EditController.php
=> [TASK] Remove unused code

Resources/Private/Language/locallang.xlf
=> Change text of createRequestWaitingForAdminConfirm localization

.github/workflows/testing.yaml, Classes/Controller/UserBackendController.php, Classes/Controller/UserController.php, Classes/Domain/Validator/AbstractValidator.php, Documentation/Features/ShowListUsers/Index.rst
=> Fix GitHub Actions

Classes/Controller/EditController.php, Classes/Utility/ObjectUtility.php
=> [BUGFIX] changing image only

ext_localconf.php
=> [BUGFIX] wrong default action for resend plugin
