in2code-de/femanager

- Resources/Public/JavaScripts/Femanager.js
- Resources/Public/JavaScripts/Validation.js
Because jQuery is saving data-attribute in own $.cache object. You can't in easy way external change data in attribute like data-validation because after that element.dataset has a different state then $(element).data(). 
I prefer use $.attr('data-*') instead of $.data(). Please take it to your consideration, because right now, you can't set your data-validation rule on fly without deleting $.cache object before.
> [BUGFIX] Change jQuery data function on attr to prevent cacheable attribute data

- Classes/Utility/UserUtility.php
Ensure the requested user is logged in, not the first with the same username.
Copied from https://forge.typo3.org/issues/79745
> [BUGFIX] Fix autologin with reused username

- Classes/Controller/AbstractController.php
- Resources/Private/Templates/Email/CreateNotify.html
This patch adds the possibility for an admin to delete an account after
the user finished the double opt process.
> [FEATURE] add link to delete account in admin notification

- Classes/Controller/AbstractController.php
Currently admin notifications are sent only if the flexform field in the plugin
is filled with an email address.
This patch adds the possibility to enable admin notification also via TypoScript.
When sending the mail, the email address from TypoScript takes precedence over
the adresse from the flexform in case both are filled.
> [FEATURE] enable admin notification via TypoScript

- Resources/Private/Language/locallang.xlf
"you're" is short for "you are". I'm sure, that's not what you want to say.
> Fix typo in local lang file

- Classes/Controller/EditController.php
For updating external data (like e.g. LDAP) it's important to have the password before hashing.
> Add signal before converting password

- Classes/Controller/EditController.php
Due to possibility to not convert password, the other signal is enough to handle changes.
> Remove signal "BeforePasswordConvert"

- Classes/Utility/ObjectUtility.php
Error to be fixed:
( ! ) Parse error: syntax error, unexpected ':', expecting ';' or '{' in 
/path/to/typo3conf/ext/femanager/Classes/Utility/ObjectUtility.php on line 110
> [BUGFIX] Fix PHP parse error in backend module 2.6.1

- Classes/Eid/ValidateEid.php
when rootpage id is different from 1, validateEid always returns a 404 error. Seems that passing a 0 pid solves that.
> rootpage id different from 1

- Classes/ViewHelpers/Validation/FormValidationDataViewHelper.php
See Issue #77 :
Reversed logic for isSimpleValidation - method by changing extendedValidations-array to a simpleValidations-array (and corresponding values).
This way, custom validators work as documented again.
> Fix broken custom validators by reversing isSimpleValidation-logic

- composer.json
In order to support TYPO3 CMS subtree split packages, introduced with v9.0.0 and backported to v8.7.7, the _typo3/cms_ package must not be used as dependency.
Furthermore, since _helhum/typo3-composer-setup_ is crucial to an operative TYPO3 CMS installation when using subtree split packages, the minimum core version has to be raised to v8.7.10 while developing.
See also:
https://typo3.org/article/typo3-v900-launched/#c7785
> Support TYPO3 CMS subtree split packages

- Documentation/FAQ/Index.rst
- Documentation/Features/Index.rst
- Documentation/Features/ResendUserConfirmationRequest/Images.txt
- Documentation/Features/ResendUserConfirmationRequest/Index.rst
- Documentation/Features/Signals/Index.rst
- Documentation/Index.rst
- Documentation/Installation/Index.rst
- Documentation/Settings.yml
- Documentation/Upgrade/Index.rst
This also brings back the sub-page "Features/ResendUserConfirmationRequest" which was not included anymore because of a typo in the file name.
Closes #135.
> [DOCS] Fix multiple errors and warnings

- Classes/Controller/AbstractController.php
Get the sender name from typoscript settings for two E-Mails (createUserConfirmation and createUserNotify).
> [BUGFIX] fix email settings

- Classes/DataProcessor/ImageManipulation.php
- Classes/Utility/AbstractUtility.php
- Classes/Utility/ObjectUtility.php
- Classes/Utility/UserUtility.php
The method to get an instance of the ConnectionPool class has been
renamed from AbstractUtility::getDatabaseConnection() to
getConnectionPool() and made public (instead of extending its visibility
in AbstractUtility).
> [TASK] Consistent naming for ConnectionPool method

- Documentation/Features/NewFields/Index.rst
In case You are running PHP 7 and have issues like "PHP Warning: Declaration of Vendor\Extension\Controller\NewController::createAction(Vendor\Extension\Domain\Model\User $user) should be compatible with In2code\Femanager\Controller\NewController::createAction(In2code\Femanager\Domain\Model\User $user) in..."
> PHP7 solution

- Configuration/TCA/Overrides/fe_users.php
- Configuration/TCA/tx_femanager_domain_model_log.php
As I checked the changed parts already apply for the TYPO3 v8.7 version.
> do TCA migrations for TYPO3 v9.5

- Classes/Domain/Repository/PluginRepository.php
Use the FlexFormService in isViewInPluginConfiguration method rather than preg_match
Resolve: #177
To reproduce:
This issue happened with the edit view with the option BE.flexformForceCDATA set to true, with 3 languages I had to re-save all of them for the error to occur again.
> [BUGFIX] Take into account the option BE.flexformForceCDATA

- Classes/Domain/Validator/AbstractValidator.php
- Tests/Unit/Domain/Validator/AbstractValidatorTest.php
As 0 is a value, and not nothing.
Relates: https://github.com/in2code-de/femanager/issues/52
> Allow '0' if field is required

- Classes/UserFunc/StaticInfoTables.php
Since CountryZonesDataProvider relies on Extbase injection, it needs to be instantiated with the Extbase ObjectManager.
This fixes "Call to a member function findAllowedByIsoCodeA3() on null" in 
https://github.com/in2code-de/femanager/blob/v5/Classes/DataProvider/CountryZonesDataProvider.php#L67
> Use ObjectManager to instantiate CountryZonesDataProvider

- Classes/Utility/BackendUserUtility.php
The property userTS of the Class TYPO3\CMS\Core\Authentication\BackendUserAuthentication is now protected.
So we have to use the provided getter.
> [BUGFIX] Use getter for userTS

- Classes/Controller/NewController.php
This fixes the error below that occurs when after creating a new user but not having specified a redirect via TS for that action.
Patch is applicable for version 5.4.2.
```
Sorry, the requested view was not found.
No template was found. View could not be resolved for action 
"create" in class "In2code\Femanager\Controller\NewController".
```
Related: #295, #299
> [BUGFIX] Template missing for New->create

- ext_localconf.php
Migration Breaking: #92609 v11.0 - Use controller classes when registering plugins/modules
> Migration Breaking: #92609 v11.0

- Classes/DataProvider/CountryDataProvider.php
- Classes/UserFunc/StaticInfoTables.php
- Classes/ViewHelpers/Form/GetCountriesFromStaticInfoTablesViewHelper.php
… name by default
It's easier for FE Users to find their country if the list displays the countries short name localized instead of official name. Eg.:
"United Kingdom" instead of "United Kingdom of Great Britain and Northern"
"Deutschland" instead of "Bundesrepublik Deutschland"
"Italia" instead of "Repubblica Italiana"
Also, it's easier for a BE editor to find a country in a long list if countries are displayed with their short name instead of official name.
> [TASK] Use country short name instead of official name by default

- Configuration/TypoScript/Main/setup.txt
Seems that scenario with `config.no_cache` causes waiting for cache locks when multiple concurrent users are calling the script.
I did a simple test with siege, and 10 concurrent users, and got almost 5x faster results.
It would be cool, if somebody could rerun the tests on his side to validate my findings.
> Use USER_INT instead of no_cache for better performance

- Classes/Domain/Validator/PasswordValidator.php
- Classes/Domain/Validator/ServersideValidator.php
- Resources/Private/Partials/Misc/FormErrors.html
- Resources/Private/Partials/Misc/ResendConfirmation.html
This fixes the output of field names in error messages.
Additionally, the argument name for a field in an error message was changed from 'code' to 'field'.
Resolves: #368
> [BUGFIX] Fix field validation messages

- Classes/Controller/AbstractController.php
Reverts 51debb9c9e568892b2d2157d21358a341a7a2224 and renders the cObj from TypoScript instead. `\In2code\Femanager\Domain\Service\SendMailService::send()` requires the fourth argument to be string.
Fixes #390
> [BUGFIX] Email subject for sendCreateUserConfirmationMail

- Classes/Domain/Service/SendMailService.php
This should fix #311 and #343.
Symfony Email class no longer returns the cid:abc123 identifier for
the inline attachment from embedFromPath. Instead we can control the
cid identifier by setting the embed part name.
Another issue was that prepareMailObject replaced the body object of
the Email with its own TextPart object. This is incorrect, as the
body should be a Multipart object that contains the html/text as
well as the embedded images. If we do not setBody ourselves, but
keep to just setting html, the Email object will generate the right
body object itself.
See [\Symfony\Component\Mime\Email::generateBody](https://github.com/symfony/mime/blob/ae887cb3b044658676129f5e97aeb7e9eb69c2d8/Email.php#L411)
Add a TypoScript configuration to embed an image, then reference it
in the Fluid …
> Fix embedded images in emails

- Classes/Controller/UserBackendController.php
The function `UserBackendController::getFrontendRequest` was introduced in 8167dd4a550603c1fc211ebe8d920050fa0f7e75 but applied incorrectly in the `refuseUserAction`. 
In addition to adding the missing arguments, I remove the call to `userRepository->remove()` 
because the function `NewController::statusAdminConfirmationRefused` already removes the user
when the frontend request succeeds.
> Fix refusing users from the admin confirmation backend list. fixes #378

- Classes/Controller/AbstractController.php
Got the following problem with createUserNotify and createAdminNotify mails:
`Argument 4 passed to In2code\Femanager\Domain\Service\SendMailService::send() must be of the type string, null given, called in / ... /femanager/Classes/Controller/AbstractController.php on line 255`
Fixed it the same way as this one: https://github.com/in2code-de/femanager/commit/4307693f379cccab3f7d4fec8e4ee463434776b4
> [BUGFIX] Fix email subject for createUserNotify and createAdminNotify

- Documentation/Features/NewFields/Index.rst
Relates #367 and #379
I'm not sure, if we still need to override the controllers in TYPO3 10.4, if we just want to extend the domain model. If we use `$extbaseObjectContainer->registerImplementation()` to register the extended model, Extbase should handle this.
Perhaps we need this in the the ext_tables.php to let the rest of TYPO3 know about the extended model:
```
$GLOBALS['TYPO3_CONF_VARS']['SYS']['Objects'][\In2code\Femanager\Domain\Model\User::class] = [
'className' => \In2code\Femanagerextended\Domain\Model\User::class,
];
```
> [BUGFIX] no custom controller needed in TYPO3 10

- Classes/DataProcessor/CleanUserGroup.php
If there is no usergroup selected in the registration and the form is submitted it brakes before the validation is executed with the error "Cannot unset string offsets" in Line 18 of femanager/Classes/DataProcessor/CleanUserGroup.php
> [FIX] Fixes CleanUserGroup DataProcessor

- Classes/Utility/UserUtility.php
Without this, the session is persisted to the database, but not updated inside TSFE and so the setting of the dummy data wipes out the user id and effectively logs off the user.
> Re-fetch session from database to update 'userSession' property of TSFE.

- Classes/Controller/AbstractController.php
- Documentation/Changelog/Index.rst
UserUtility::getDirtyPropertiesFromUser() expects the new, changed user data and compares that against the old user data. So comparing the existing user data against itself caused that changes were never submitted in the `notifyAdmin` email.
Notification email to admin is also sent when adding recipient's address to flex form only
This is a backport to v5.
> Backport of Bugfix: admin confirmation mail problems

- Classes/Controller/AbstractController.php
- Classes/Utility/ConfigurationUtility.php
- Documentation/Changelog/Index.rst
UserUtility::getDirtyPropertiesFromUser() expects the new, changed user data and compares that against the old user data. So comparing the existing user data against itself caused that changes were never submitted in the `notifyAdmin` email.
> [BUGFIX] Notification mail to admin shows changes

- Classes/Controller/AbstractController.php
- Configuration/TypoScript/Main/setup.typoscript
- Documentation/Installation/Index.rst
- ext_typoscript_setup.typoscript
The removed configuration can only be overwritten by another preset file in another extension, it can not be overwritten by PageTS.
> [TASK] Removes configPID from ext_typoscript_setup.typoscript

- Classes/Controller/AbstractController.php
- Classes/Utility/ConfigurationUtility.php
- Configuration/TypoScript/Main/setup.typoscript
Corrected config paths, added second parameter to getValue() method calls and added the check if admin notificatin is enabled in general to notifyAdminAboutEdits().
> BUGFIX: missing email AdminNotify after editing of user profile

- Classes/DataProcessor/ImageManipulation.php
Updated property name to camelcase for domain model field.
For example: If you have custom field with domain modeling format such as `tx_example_domain_model_documents` it won't work and throw error. this will convert field name in camel case and it will work!
> [BUGFIX] Fixed issue with custom upload field

- Classes/Domain/Validator/ServersideValidator.php
The ServersideValidator should not re-evaluate the `$value` variable after it has been set to an UID. `method_exists` on an integer value will fail with an exception. Instead, a possible evaluated `uid` should be returned directly.
Refs #503
> [BUGFIX] Do not re-evaluate object values in ServersideValidator

- Classes/Utility/UserUtility.php
This change ensures, that `ObjectUtility::implodeObjectStorageOnProperty()` is only used, when the evaluated object is of type `ObjectStorage`. For all other objects, the `uid` values are compared.
Refs #505
> [BUGFIX] Add full object support in getDirtyPropertiesFromUser()

- Classes/Controller/AbstractController.php
In case the module is used outside of a page with a TypoScript template, there is no `configPID` defined. In this case, the template of the current page will be used.
Relates: #442
Resolves: #502
> [BUGFIX] Prevent undefined array key for empty configPID

- Classes/Controller/AbstractController.php
Its a working solution to restore the flexform email notification to admin after registration.
resolve #472, see https://github.com/in2code-de/femanager/issues/472#issuecomment-1476492996
> [BUGFIX] Restore email notification to admin after registration

- Resources/Private/Partials/Fields/Terms.html
This way, the user will not lose the data in the form.
> [BUGFIX] Open the "terms & conditions" page in a new tab

- Resources/Private/Language/locallang.xlf
- Resources/Private/Language/locallang_db.xlf
The English spelling for "diverse" (the gender) is "diverse", not "divers".
> [BUGFIX] Fix a typo in the labels

- composer.json
This fixes an interactive question when running `composer install` or `composer update` with Composer V2.7.
Also sort the allowed Composer plugins for better maintainability.
> [BUGFIX] Allow the PHPStan extension installer for Composer

- rector.php
The V7 branch of this extension still needs to support PHP 7.4 (to fully support TYPO3 11LTS). So the Rector PHP target version needs to be 7.4., not 8.1.
Releases: v7
> [BUGFIX] Fix the Rector PHP target version

- composer.json
When Composer scripts call other Composer scripts, the called script needs to be prefixed with `@`.
Also call the existing Rector script for consistency instead of calling Rector directly.
> [BUGFIX] Fix composer script calls in the `test:rector:fix` script

- Resources/Private/Templates/Edit/ConfirmUpdateRequest.html
- Resources/Private/Templates/Edit/Edit.html
- Resources/Private/Templates/Invitation/Edit.html
- Resources/Private/Templates/Invitation/New.html
- Resources/Private/Templates/New/New.html
- Resources/Private/Templates/New/ResendConfirmationDialogue.html
Successor to #304 containing only the fix of passing the proper parameter to the form error partial.
> [BUGFIX] Pass proper argument to form error partial

- composer.json
Since TYPO3 12.4.10 the core allows Symfony 7 in its dependencies (`"symfony/config:^6.4 || ^7.0"`)
@see https://forge.typo3.org/issues/102746
Related: #552
> [TASK] Update Symfony dependency

- Classes/Domain/Validator/CaptchaValidator.php
- Classes/Domain/Validator/ClientsideValidator.php
`utf8_decode` has been deprecated, and calling it in PHP >= 8.2 throws a deprecation warning.
This change bringt the two affected calls in line with what we already have in `main` in this commit:
134418314d6db55d463bd0aa882942ba10710c1b
https://www.php.net/manual/en/function.utf8-decode.php
> [BUGFIX] Avoid deprecated PHP function `utf8_decode`

- Documentation/Features/Events/Index.rst
Archiving better readability by adding a real header.
Currently the first row of data does show up as the table header.
See image:
> Add header row to Features/Events/Index.rst

- Classes/Controller/AbstractController.php
- Classes/Controller/EditController.php
- Classes/Domain/Model/User.php
In the rare case that crdate is null for a user, this now picks the 0 DateTime as an option right in the spots where the token is created instead of inside the User model
Closes #430
> Remove side-effect in User crdate getter

- Configuration/TypoScript/Main/setup.typoscript
This adds `max` size validations for all default fe_user fields to the TypoScript setup of Femanager for both new/edit actions.
Fixes #605
> Add max size validations for default fe_user fields

- Classes/Controller/AbstractController.php
> Use configured receiver name in `createAdminNotify`

- Classes/Middleware/RemovePasswordIfEmptyMiddleware.php
Fixes in2code-pro/femanager#36 
* Skips the entire logic if we're not on a `tx_femanager_edit` action
* Removes the second fetch of the request body from the request object, reutilizing the initally acquired request body for the outside conditional check
> Clean up RemovePasswordIfEmptyMiddleware

- Classes/Controller/EditController.php
- Classes/Controller/InvitationController.php
f:translate requires the request object to resolve the extension name for localization strings, so pass them to the mail service whenever it's available
> [BUGFIX] Pass request object to mail service in controller context

- Classes/Controller/AbstractController.php
- Classes/Controller/EditController.php
- Classes/Controller/InvitationController.php
- Classes/Controller/NewController.php
- Classes/Domain/Validator/ClientsideValidator.php
This PR includes 2 fixes for the `sr_freecap` captcha integration:
1. `sr_freecap`'s `WordRepository` needs a valid Request to work with. This works fine in serverside validation, but in AJAX/client-side validation the initialized repository doesn't have a Request at hand and thus crashes form submissions with a HTTP 500 error. We simply pass an available request or `$GLOBALS['TYPO3_REQUEST']` instead.
2. If you have `sr_freecap` installed and in server-side validation mode, you could leave the Captcha field empty and forms would still submit fine.
The `CaptchaValidator` is skipped when the `captcha` parameter is empty. This causes forms to pass when you just leave the Captcha input untouched.
This PR adds a `validateMissingCaptcha` method to `AbstractController` which checks for the …
> sr_freecap integration fixes
